force-app/main/default/objects/RSC_Complaint__c/RSC_Complaint__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint</label>
    <nameField>
        <displayFormat>RSC-CN-{0000}</displayFormat>
        <label>RSC Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint__c/fields/RSC_Complaint_Category__c.field-meta.xml
<CustomField>
    <fullName>RSC_Complaint_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSC Complaint Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RSC_Complaint_Category__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>RSC_Complaint_Category__c</referenceTo>
    <relationshipLabel>RSC Complaints</relationshipLabel>
    <relationshipName>RSC_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Info</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint_Category__c/RSC_Complaint_Category__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint Category</label>
    <nameField>
        <displayFormat>RSC-C-C-{0000}</displayFormat>
        <label>RSC Complaint Category Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaint Categorys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint_Category__c/fields/Category_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Label__c</fullName>
    <label>Category Label</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RSCComplaintPortalHomelHandler.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : RSCComplaintPortalHomelHandler
 * Author          : Sandeep.R
 * Created Date    : Jan 15, 2026
 * Last Modified By: Sandeep.R
 * Last Modified On: Jan 15, 2026
 * Description     : Handler class for rscComplaintPortalHomel LWC Component
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 15, 2026  │ Sandeep.R    │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public with sharing class RSCComplaintPortalHomelHandler {

	@AuraEnabled(cacheable=true)
	public static List<RSC_Complaint__c> getComplaints() {
		List<RSC_Complaint__c> complaintList = [SELECT Id, Name, Subject__c, Complaint_Description__c, Status__c, RSC_Complaint_Category__r.Name, RSC_Complaint_Category__r.Category_Label__c FROM RSC_Complaint__c WITH SECURITY_ENFORCED ORDER BY Name DESC];
		return complaintList;
	}

}