force-app/main/default/objects/RSC_Complaint__c/RSC_Complaint__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint</label>
    <nameField>
        <displayFormat>RSC-CN-{0000}</displayFormat>
        <label>RSC Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RSC_Complaints1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Standard Platform User</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSC_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/RSC_Complaint_Category__c.field-meta.xml
<CustomField>
    <fullName>RSC_Complaint_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSC Complaint Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RSC_Complaint_Category__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>RSC_Complaint_Category__c</referenceTo>
    <relationshipLabel>RSC Complaints</relationshipLabel>
    <relationshipName>RSC_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Info</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint_Category__c/RSC_Complaint_Category__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint Category</label>
    <nameField>
        <displayFormat>RSC-C-C-{0000}</displayFormat>
        <label>RSC Complaint Category Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaint Categorys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint_Category__c/fields/Category_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Label__c</fullName>
    <label>Category Label</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint_Category__c/fields/Priotiy__c.field-meta.xml
<CustomField>
    <fullName>Priotiy__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSC_SLA__c/RSC_SLA__c.object-meta.xml
<CustomObject>
    <label>RSC_SLA</label>
    <nameField>
        <displayFormat>RSC-SLA-{0000}</displayFormat>
        <label>RSC_SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC_SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_SLA__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSC_SLA__c/fields/RSC_Complaint__c.field-meta.xml
<CustomField>
    <fullName>RSC_Complaint__c</fullName>
    <label>RSC Complaint</label>
    <referenceTo>RSC_Complaint__c</referenceTo>
    <relationshipLabel>RSC_SLAs</relationshipLabel>
    <relationshipName>RSC_SLAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RSC_SLA__c/fields/SLA_Count__c.field-meta.xml
<CustomField>
    <fullName>SLA_Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>SLA Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SLA_Notification_Test.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : SLA_Notification_Test
 * Author          : Sandeep.R
 * Created Date    : Jan 15, 2026
 * Last Modified By: Sandeep.R
 * Last Modified On: Jan 15, 2026
 * Description     : Test class for SLA_Notification
 *
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 15, 2026  │ Sandeep.R    │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
@isTest
public class SLA_Notification_Test {
    @TestSetup
    static void makeData(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User approver = new User(
            Alias = 'apprv',
        Email = 'approver@test.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'Approver',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'Asia/Kolkata',
        Username = 'approver' + System.currentTimeMillis() + '@test.com'
            );
        
        User agent = new User(
            Alias = 'agent',
        Email = 'agent@test.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'Agent',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'Asia/Kolkata',
        Username = 'agent' + System.currentTimeMillis() + '@test.com'
            );
        
        insert new List<User>{ approver, agent };
        
        // Fetch Permission Set
        PermissionSet ps = [
    SELECT Id 
    FROM PermissionSet 
    WHERE Name = 'RSC_Manager_Permission' 
    LIMIT 1
];
        //User uId = [SELECT Id FROM User WHERE Id = :agent.Id LIMIT 1];
        
        // Assign Permission Set to Agent User
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = agent.Id,
        PermissionSetId = ps.Id
            );
        insert psa;
        
        List<Group> queueList = new List<Group>();
        
        // Create Queue
        Group qUrgent = new Group(
            Name = 'RSC_Urgent',
        Type = 'Queue'
            );
        queueList.add(qUrgent);
        
        Group qHigh = new Group(
            Name = 'RSC_High',
        Type = 'Queue'
            );
        queueList.add(qHigh);
        
        Group qMedium = new Group(
            Name = 'RSC_Medium',
        Type = 'Queue'
            );
        queueList.add(qMedium);
        
        Group qNormal = new Group(
            Name = 'RSC_Normal',
        Type = 'Queue'
            );
        queueList.add(qNormal);
        insert queueList;
        
        List<GroupMember> queueMemberList = new List<GroupMember>();
        // Add user to queue
        for(integer i=0; i < queueList.size(); i++){
            queueMemberList.add( new GroupMember(
                GroupId = queueList[i].Id,
            UserOrGroupId = agent.Id
                ));
        }
        insert queueMemberList;
        User UserInfo = [SELECT Id, Name, Username FROM User WHERE Id = :agent.id WITH SECURITY_ENFORCED];
        System.runAs(UserInfo)
        {
            List<RSC_Complaint_Category__c> categoryList = new List<RSC_Complaint_Category__c>();
            categoryList.add( new RSC_Complaint_Category__c(
                Category_Label__c = 'Category Urgent',
            Priotiy__c = 'Urgent'
                ));
            categoryList.add( new RSC_Complaint_Category__c(
                Category_Label__c = 'Category High',
            Priotiy__c = 'High'
                ));
            categoryList.add( new RSC_Complaint_Category__c(
                Category_Label__c = 'Category Medium',
            Priotiy__c = 'Medium'
                ));
            categoryList.add( new RSC_Complaint_Category__c(
                Category_Label__c = 'Category Normal',
            Priotiy__c = 'Normal'
                ));
            
            insert categoryList;
            
            List<RSC_Complaint__c> complaintList = new List<RSC_Complaint__c>();
            complaintList.add( new RSC_Complaint__c(
                Subject__c = 'Test Complaint Normal',
                Status__c = 'In Progress',
            RSC_Complaint_Category__c = categoryList[3].Id
                ));
            complaintList.add( new RSC_Complaint__c(
                Subject__c = 'Test Complaint Medium',
                Status__c = 'In Progress',
            RSC_Complaint_Category__c = categoryList[2].Id
                ));
            complaintList.add( new RSC_Complaint__c(
                Subject__c = 'Test Complaint High',
                Status__c = 'In Progress',
            RSC_Complaint_Category__c = categoryList[1].Id
                ));
            complaintList.add( new RSC_Complaint__c(
                Subject__c = 'Test Complaint Urgent',
                Status__c = 'In Progress',
            RSC_Complaint_Category__c = categoryList[0].Id
                ));
            
            // RSC_Complaint__c complaint = new RSC_Complaint__c(
            //     Subject__c = 'Test Complaint Assigne',
            // Assigned_To__c = agent.Id,
            // Approved_By__c = approver.Id,
            // OwnerId = q.Id
            //     );
            //complaintList.add(complaint);
            
            insert complaintList;
        }
        
    }
    
    @IsTest
    static void testFirst(){
        User UserInfoD = [SELECT Id FROM User WHERE Email = 'agent@test.com' LIMIT 1];
        System.runAs(UserInfoD)
        {
        List<RSC_Complaint__c> complaintDetails = [SELECT Id, Status__c, Priority__c, Is_Approved__c FROM RSC_Complaint__c];
        System.debug('complaintDetails'+complaintDetails);
        for(RSC_Complaint__c comp : complaintDetails){
            comp.Status__c = 'In Progress';
            comp.Is_Approved__c = true;
            comp.Approved_By__c = UserInfoD.Id;
            comp.Approval_Date__c = System.now();
        }
        update complaintDetails;
        System.debug('complaintDetails 173'+[SELECT Id, Status__c, Priority__c, Is_Approved__c FROM RSC_Complaint__c]);
        
        List<RSC_SLA__c> slaDetails = [SELECT Id, Priority__c FROM RSC_SLA__c];
        System.debug('slaDetails'+slaDetails);
        for(RSC_SLA__c sla : slaDetails){
            if(sla.Priority__c == 'Normal'){
                sla.SLA_Count__c = 2;
            } else if (sla.Priority__c == 'Medium'){
                sla.SLA_Count__c = 3;
            }
        }
        update slaDetails;
    }
        
        Test.startTest();
        SLA_Notification slaNotification = new SLA_Notification();
        Database.executeBatch(slaNotification, 100);
        Test.stopTest();
        List<RSC_Complaint__c> complaintDetails = [SELECT Id FROM RSC_Complaint__c WITH SECURITY_ENFORCED];
        System.Assert.areEqual(false, complaintDetails.isEmpty(), 'Complaint List is Not Empty');
    }
}