force-app/main/default/objects/RSC_Complaint__c/RSC_Complaint__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint</label>
    <nameField>
        <displayFormat>RSC-CN-{0000}</displayFormat>
        <label>RSC Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RSC_Complaints1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Standard Platform User</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSC_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/RSC_Complaint_Category__c.field-meta.xml
<CustomField>
    <fullName>RSC_Complaint_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSC Complaint Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RSC_Complaint_Category__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>RSC_Complaint_Category__c</referenceTo>
    <relationshipLabel>RSC Complaints</relationshipLabel>
    <relationshipName>RSC_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint_Category__c/RSC_Complaint_Category__c.object-meta.xml
<CustomObject>
    <label>RSC Complaint Category</label>
    <nameField>
        <displayFormat>RSC-C-C-{0000}</displayFormat>
        <label>RSC Complaint Category Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSC Complaint Categorys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RSC_Complaint_Category__c/fields/Category_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Label__c</fullName>
    <label>Category Label</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RSC_Complaint_Category__c/fields/Priotiy__c.field-meta.xml
<CustomField>
    <fullName>Priotiy__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RSCComplaintTriggerHandlerTest.cls
@isTest
private class RSCComplaintTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        List<RSC_Complaint_Category__c> categoryList = new List<RSC_Complaint_Category__c>();
        categoryList.add( new RSC_Complaint_Category__c(
            Category_Label__c = 'Category Urgent',
        Priotiy__c = 'Urgent'
            ));
        categoryList.add( new RSC_Complaint_Category__c(
            Category_Label__c = 'Category High',
        Priotiy__c = 'High'
            ));
        categoryList.add( new RSC_Complaint_Category__c(
            Category_Label__c = 'Category Medium',
        Priotiy__c = 'Medium'
            ));
        categoryList.add( new RSC_Complaint_Category__c(
            Category_Label__c = 'Category Normal',
        Priotiy__c = 'Normal'
            ));
        
        insert categoryList;
        
        List<RSC_Complaint__c> complaintList = new List<RSC_Complaint__c>();
        complaintList.add( new RSC_Complaint__c(
            Subject__c = 'Test Complaint Normal',
        RSC_Complaint_Category__c = categoryList[3].Id
            ));
        complaintList.add( new RSC_Complaint__c(
            Subject__c = 'Test Complaint Medium',
        RSC_Complaint_Category__c = categoryList[2].Id
            ));
        complaintList.add( new RSC_Complaint__c(
            Subject__c = 'Test Complaint High',
        RSC_Complaint_Category__c = categoryList[1].Id
            ));
        complaintList.add( new RSC_Complaint__c(
            Subject__c = 'Test Complaint Urgent',
        RSC_Complaint_Category__c = categoryList[0].Id
            ));
        
        // RSC_Complaint__c complaint = new RSC_Complaint__c(
        //     Subject__c = 'Test Complaint Assigne',
        // Assigned_To__c = agent.Id,
        // Approved_By__c = approver.Id,
        // OwnerId = q.Id
        //     );
        //complaintList.add(complaint);
        
        insert complaintList;
    }
    @isTest
    static void myUnitTest() {
        List<Id> complaintIds = new List<Id>();
        for(RSC_Complaint__c complaint : [SELECT Id FROM RSC_Complaint__c]){
            complaintIds.add(complaint.Id);
        }
        Test.startTest();
            RSCComplaintTriggerHandler.sendEmailWithAttachment(complaintIds);
        Test.stopTest();

        System.assert.areEqual(false, complaintIds.isEmpty());
    }
}